% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Football Findings},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Football Findings}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

This work was made in order to find some useful insights in football.

We hope to find external and internal factors that could affect results
in general such as time, League, playing as Local, etc.

That could be useful for making more informed decisions in bets.

The data used in this work was scraped from
\url{https://www.espn.com/soccer/and} organized by JOSEPH MOHR. It
includes data for over 2300 matches and information about the top 6
European Leagues.

\hypertarget{importing-libraries}{%
\section{Importing libraries}\label{importing-libraries}}

For this document we are going to use different cleaning and
manipulation tools and functions from different libraries. In this case,
we import them at the beginning.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyr)}
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(skimr)}
\FunctionTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

\hypertarget{importing-data}{%
\section{Importing data}\label{importing-data}}

For this case study, we are going to use two tables

\hypertarget{importing-the-first-table}{%
\subsection{Importing the first table}\label{importing-the-first-table}}

This table has data about all the matches of the main 6 Leagues in
Europe from 2000 to 2021.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"matches.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{importing-the-second-table}{%
\subsection{Importing the second
table}\label{importing-the-second-table}}

This table has data about the number of games played, win games, lost
games, number of points of each team for the seasons from 2000 to 2021.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{summary }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"all\_tables.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{analizing-the-distribution-of-the-first-table.}{%
\section{Analizing the distribution of the first
table.}\label{analizing-the-distribution-of-the-first-table.}}

We are going to start working with the table ``matches''.

\begin{Shaded}
\begin{Highlighting}[]
 \FunctionTok{skim\_without\_charts}\NormalTok{(matches) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: There was 1 warning in `dplyr::summarize()`.
## i In argument: `dplyr::across(tidyselect::any_of(variable_names),
##   mangled_skimmers$funs)`.
## i In group 0: .
## Caused by warning:
## ! There were 150 warnings in `dplyr::summarize()`.
## The first warning was:
## i In argument: `dplyr::across(tidyselect::any_of(variable_names),
##   mangled_skimmers$funs)`.
## Caused by warning in `sorted_count()`:
## ! Variable contains value(s) of "" that have been converted to "empty".
## i Run ]8;;ide:run:dplyr::last_dplyr_warnings()dplyr::last_dplyr_warnings()]8;; to see the 149 remaining warnings.
\end{verbatim}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule()
\endhead
Name & matches \\
Number of rows & 25724 \\
Number of columns & 210 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
factor & 159 \\
numeric & 51 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule()
\end{longtable}

\textbf{Variable type: factor}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0952}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1333}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0762}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0857}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4095}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ordered
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
top\_counts
\end{minipage} \\
\midrule()
\endhead
home & 0 & 1 & FALSE & 204 & Man: 400, Tot: 400, Eve: 399, Ars: 398 \\
away & 0 & 1 & FALSE & 203 & Ars: 400, Liv: 400, Che: 399, Eve: 398 \\
date & 0 & 1 & FALSE & 1525 & Sat: 82, Sat: 80, Sat: 77, Sat: 75 \\
time..utc. & 0 & 1 & FALSE & 75 & 15:: 3084, 14:: 2675, 13:: 2368, 14::
1977 \\
attendance & 0 & 1 & FALSE & 13284 & emp: 4320, 30,: 194, 15,: 191, 20,:
186 \\
venue & 0 & 1 & FALSE & 306 & emp: 1519, Old: 381, Goo: 380, Anf: 379 \\
league & 0 & 1 & FALSE & 75 & 201: 383, 200: 381, 200: 381, 200: 380 \\
part\_of\_competition & 0 & 1 & FALSE & 18 & na: 21755, Re: 1512, 20:
306, 20: 306 \\
game\_status & 0 & 1 & FALSE & 4 & FT: 25710, Aba: 12, AET: 1, FT-: 1 \\
shootout & 0 & 1 & FALSE & 2 & Fal: 25723, Tru: 1 \\
home\_possessionPct & 0 & 1 & FALSE & 74 & emp: 2031, 50\%: 884, 51\%:
879, 55\%: 875 \\
away\_possessionPct & 0 & 1 & FALSE & 74 & emp: 2031, 50\%: 884, 49\%:
879, 45\%: 875 \\
home\_shotsSummary & 0 & 1 & FALSE & 435 & emp: 2031, 0 (: 394, 11 :
385, 12 : 378 \\
away\_shotsSummary & 0 & 1 & FALSE & 341 & emp: 2031, 10 : 521, 9 (:
513, 8 (: 478 \\
home\_goal\_minutes & 0 & 1 & FALSE & 10494 & emp: 5791, 56': 100, 67':
98, 59': 93 \\
home\_goal\_scorers & 0 & 1 & FALSE & 14440 & emp: 5791, Ari: 25, Dar:
22, Jer: 22 \\
away\_goal\_minutes & 0 & 1 & FALSE & 7749 & emp: 8307, 82': 117, 81':
116, 50': 115 \\
away\_goal\_scorers & 0 & 1 & FALSE & 11475 & emp: 8307, Cri: 25, Iag:
24, Pie: 23 \\
home\_starting\_1\_num & 0 & 1 & FALSE & 105 & 1.0: 10382, 1: 3991, 13.:
3244, 25.: 1038 \\
home\_starting\_1 & 0 & 1 & FALSE & 792 & Man: 231, Pep: 226, Dav: 222,
Pet: 220 \\
home\_starting\_2\_num & 0 & 1 & FALSE & 119 & 5.0: 2183, 4.0: 2119,
6.0: 1766, 3.0: 1439 \\
home\_starting\_2 & 0 & 1 & FALSE & 2011 & Mat: 164, Iñi: 159, Die: 157,
emp: 143 \\
home\_starting\_3\_num & 0 & 1 & FALSE & 113 & 5.0: 2351, 4.0: 2045,
3.0: 1965, 6.0: 1529 \\
home\_starting\_3 & 0 & 1 & FALSE & 2124 & Rya: 146, Gar: 145, Ger: 144,
emp: 143 \\
home\_starting\_4\_num & 0 & 1 & FALSE & 113 & 3.0: 3454, 5.0: 1244,
6.0: 1011, 4.0: 980 \\
home\_starting\_4 & 0 & 1 & FALSE & 2837 & Lei: 159, emp: 143, Mar: 141,
Fil: 139 \\
home\_starting\_5\_num & 0 & 1 & FALSE & 126 & 2.0: 3325, 3.0: 1068,
22.: 916, 5.0: 912 \\
home\_starting\_5 & 0 & 1 & FALSE & 2995 & Jua: 189, Dan: 153, Kyl: 147,
emp: 143 \\
home\_starting\_6\_num & 0 & 1 & FALSE & 124 & 8.0: 1615, 6.0: 1066,
10.: 992, 14.: 927 \\
home\_starting\_6 & 0 & 1 & FALSE & 3555 & emp: 143, Ser: 141, Bru: 94,
Raú: 89 \\
home\_starting\_7\_num & 0 & 1 & FALSE & 122 & 8.0: 2488, 6.0: 1377,
10.: 1101, 14.: 1077 \\
home\_starting\_7 & 0 & 1 & FALSE & 3057 & emp: 143, And: 92, Fra: 86,
Mic: 86 \\
home\_starting\_8\_num & 0 & 1 & FALSE & 124 & 8.0: 1790, 10.: 1230,
7.0: 1075, 6.0: 1041 \\
home\_starting\_8 & 0 & 1 & FALSE & 3716 & emp: 143, Jua: 108, Luk: 101,
Xav: 95 \\
home\_starting\_9\_num & 0 & 1 & FALSE & 115 & 9.0: 2473, 10.: 1719,
7.0: 1496, 11.: 1305 \\
home\_starting\_9 & 0 & 1 & FALSE & 3586 & emp: 165, Rob: 126, Kar: 120,
Har: 107 \\
home\_starting\_10\_num & 0 & 1 & FALSE & 120 & 10.: 2371, 9.0: 2198,
11.: 1977, 7.0: 1774 \\
home\_starting\_10 & 0 & 1 & FALSE & 3222 & emp: 175, Cri: 171, Ant:
115, Son: 105 \\
home\_starting\_11\_num & 0 & 1 & FALSE & 125 & 9.0: 2266, 10.: 1451,
11.: 1437, 7.0: 1378 \\
home\_starting\_11 & 0 & 1 & FALSE & 2984 & emp: 179, Lio: 147, Nic:
109, Mar: 93 \\
home\_bench\_1\_num & 0 & 1 & FALSE & 145 & 1.0: 1583, 13.: 1384, 1:
966, 12.: 808 \\
home\_bench\_1 & 0 & 1 & FALSE & 4615 & emp: 142, Ste: 138, Boa: 108,
Stu: 96 \\
home\_bench\_1\_minute & 0 & 1 & FALSE & 6 & na: 25578, emp: 142, 18':
1, 46': 1 \\
home\_bench\_2\_num & 0 & 1 & FALSE & 146 & 1.0: 805, 13.: 784, 22.:
696, 1: 606 \\
home\_bench\_2 & 0 & 1 & FALSE & 6550 & emp: 143, Chr: 54, Adr: 50, Tob:
47 \\
home\_bench\_2\_minute & 0 & 1 & FALSE & 12 & na: 25570, emp: 143, 77':
2, 45': 1 \\
home\_bench\_3\_num & 0 & 1 & FALSE & 147 & 13.: 650, 1.0: 596, 16.:
546, 21.: 537 \\
home\_bench\_3 & 0 & 1 & FALSE & 7504 & emp: 144, Dan: 48, Raf: 47, Joe:
44 \\
home\_bench\_3\_minute & 0 & 1 & FALSE & 91 & na: 24123, emp: 144, 45':
124, 77': 48 \\
home\_bench\_4\_num & 0 & 1 & FALSE & 151 & 13.: 713, 19.: 673, 20.:
669, 15.: 660 \\
home\_bench\_4 & 0 & 1 & FALSE & 7687 & emp: 188, Cos: 37, Dav: 33, Raf:
31 \\
home\_bench\_4\_minute & 0 & 1 & FALSE & 97 & na: 23055, emp: 188, 45':
144, 76': 87 \\
home\_bench\_5\_num & 0 & 1 & FALSE & 150 & emp: 1114, 20.: 752, 8.0:
745, 19.: 699 \\
home\_bench\_5 & 0 & 1 & FALSE & 7725 & emp: 1114, Adr: 27, Jer: 27,
Sho: 27 \\
home\_bench\_5\_minute & 0 & 1 & FALSE & 105 & na: 9578, 45': 1203, emp:
1114, 82': 468 \\
away\_starting\_1\_num & 0 & 1 & FALSE & 107 & 1.0: 10330, 1: 3977, 13.:
3241, 25.: 1041 \\
away\_starting\_1 & 0 & 1 & FALSE & 823 & Man: 234, Pep: 228, Pet: 222,
Dav: 211 \\
away\_starting\_2\_num & 0 & 1 & FALSE & 113 & 5.0: 2176, 4.0: 2125,
6.0: 1785, 2.0: 1403 \\
away\_starting\_2 & 0 & 1 & FALSE & 2067 & Mat: 167, Iñi: 159, Die: 157,
Ser: 147 \\
away\_starting\_3\_num & 0 & 1 & FALSE & 117 & 5.0: 2348, 4.0: 2004,
3.0: 1968, 6.0: 1553 \\
away\_starting\_3 & 0 & 1 & FALSE & 2186 & Ger: 147, emp: 142, Gar: 139,
Jos: 137 \\
away\_starting\_4\_num & 0 & 1 & FALSE & 117 & 3.0: 2825, 3: 1182, 5.0:
962, 6.0: 838 \\
away\_starting\_4 & 0 & 1 & FALSE & 2901 & Lei: 152, Mar: 147, Nac: 147,
emp: 144 \\
away\_starting\_5\_num & 0 & 1 & FALSE & 123 & 2.0: 3294, 3.0: 1098,
5.0: 918, 22.: 830 \\
away\_starting\_5 & 0 & 1 & FALSE & 3136 & Jua: 183, Kyl: 157, emp: 150,
Dan: 150 \\
away\_starting\_6\_num & 0 & 1 & FALSE & 126 & 8.0: 1734, 6.0: 1195,
10.: 1122, 14.: 1034 \\
away\_starting\_6 & 0 & 1 & FALSE & 3686 & emp: 153, Ser: 151, Gar: 75,
Cas: 74 \\
away\_starting\_7\_num & 0 & 1 & FALSE & 125 & 8.0: 2353, 6.0: 1408,
14.: 1105, 10.: 992 \\
away\_starting\_7 & 0 & 1 & FALSE & 3195 & emp: 155, Fra: 90, Luc: 89,
Gar: 88 \\
away\_starting\_8\_num & 0 & 1 & FALSE & 123 & 8.0: 1752, 10.: 1197,
6.0: 1062, 7.0: 1059 \\
away\_starting\_8 & 0 & 1 & FALSE & 3900 & emp: 158, Luk: 102, Xav: 94,
Jua: 87 \\
away\_starting\_9\_num & 0 & 1 & FALSE & 125 & 9.0: 2404, 10.: 1576,
7.0: 1472, 11.: 1260 \\
away\_starting\_9 & 0 & 1 & FALSE & 3796 & emp: 181, Kar: 123, Rob: 119,
Lui: 108 \\
away\_starting\_10\_num & 0 & 1 & FALSE & 122 & 10.: 2375, 9.0: 2062,
11.: 1948, 7.0: 1720 \\
away\_starting\_10 & 0 & 1 & FALSE & 3370 & emp: 188, Cri: 148, Ant:
120, Son: 92 \\
away\_starting\_11\_num & 0 & 1 & FALSE & 125 & 9.0: 2679, 10.: 1902,
11.: 1733, 7.0: 1698 \\
away\_starting\_11 & 0 & 1 & FALSE & 3105 & emp: 196, Lio: 141, Nic: 97,
Way: 95 \\
away\_bench\_1\_num & 0 & 1 & FALSE & 146 & 1.0: 1613, 13.: 1385, 1:
895, 12.: 780 \\
away\_bench\_1 & 0 & 1 & FALSE & 4678 & emp: 154, Ste: 142, Boa: 108,
Jer: 99 \\
away\_bench\_1\_minute & 0 & 1 & FALSE & 8 & na: 25563, emp: 154, 75':
2, 60': 1 \\
away\_bench\_2\_num & 0 & 1 & FALSE & 146 & 13.: 1208, 1.0: 1073, 22.:
780, 5.0: 724 \\
away\_bench\_2 & 0 & 1 & FALSE & 6676 & emp: 156, Adr: 57, Chr: 51, Ser:
46 \\
away\_bench\_2\_minute & 0 & 1 & FALSE & 14 & na: 25554, emp: 156, 66':
2, 84': 2 \\
away\_bench\_3\_num & 0 & 1 & FALSE & 147 & 13.: 1014, 1.0: 810, 21.:
716, 15.: 690 \\
away\_bench\_3 & 0 & 1 & FALSE & 7600 & emp: 167, Raf: 51, Dan: 42, Iag:
41 \\
away\_bench\_3\_minute & 0 & 1 & FALSE & 95 & na: 24093, emp: 167, 45':
102, 46': 61 \\
away\_bench\_4\_num & 0 & 1 & FALSE & 154 & 19.: 702, 13.: 691, 15.:
648, 20.: 647 \\
away\_bench\_4 & 0 & 1 & FALSE & 7834 & emp: 216, Cos: 35, Raf: 35, Joe:
31 \\
away\_bench\_4\_minute & 0 & 1 & FALSE & 98 & na: 22902, emp: 216, 45':
167, 76': 80 \\
away\_bench\_5\_num & 0 & 1 & FALSE & 148 & emp: 1257, 9.0: 779, 20.:
759, 8.0: 759 \\
away\_bench\_5 & 0 & 1 & FALSE & 7786 & emp: 1257, Jer: 32, Jam: 31,
Raf: 28 \\
away\_bench\_5\_minute & 0 & 1 & FALSE & 105 & na: 9532, 45': 1282, emp:
1257, 78': 447 \\
home\_bench\_6\_num & 0 & 1 & FALSE & 153 & emp: 4096, 7.0: 800, 9.0:
791, 11.: 771 \\
home\_bench\_6 & 0 & 1 & FALSE & 6743 & emp: 4096, Adr: 30, Cla: 28,
Raú: 25 \\
home\_bench\_6\_minute & 0 & 1 & FALSE & 102 & na: 6093, emp: 4096, 45':
968, 79': 473 \\
away\_bench\_6\_num & 0 & 1 & FALSE & 142 & emp: 4190, 9.0: 957, 7.0:
894, 11.: 869 \\
away\_bench\_6 & 0 & 1 & FALSE & 6773 & emp: 4190, Oli: 31, Ádá: 28,
Adr: 26 \\
away\_bench\_6\_minute & 0 & 1 & FALSE & 105 & na: 5964, emp: 4190, 45':
1060, 75': 480 \\
away\_starting\_12 & 0 & 1 & FALSE & 473 & emp: 24797, Lui: 13, Jos: 12,
Ped: 11 \\
home\_starting\_12 & 0 & 1 & FALSE & 416 & emp: 24857, Laf: 13, Lui: 13,
Lui: 12 \\
home\_formation & 0 & 1 & FALSE & 24 & emp: 7155, 4-2: 5920, 4-4: 3593,
4-3: 2760 \\
away\_formation & 0 & 1 & FALSE & 24 & emp: 7170, 4-2: 5765, 4-4: 3224,
4-3: 2725 \\
home\_bench\_7\_num & 0 & 1 & FALSE & 136 & emp: 4492, 9.0: 1275, 11.:
1129, 7.0: 1052 \\
home\_bench\_7 & 0 & 1 & FALSE & 6183 & emp: 4492, Ped: 35, Mik: 33,
Iva: 32 \\
home\_bench\_7\_minute & 0 & 1 & FALSE & 108 & emp: 4492, na: 3806, 45':
1011, 77': 542 \\
away\_bench\_7\_num & 0 & 1 & FALSE & 129 & emp: 4660, 9.0: 1223, 11.:
1124, 7.0: 1040 \\
away\_bench\_7 & 0 & 1 & FALSE & 6306 & emp: 4660, Cla: 35, Jav: 33,
Adr: 32 \\
away\_bench\_7\_minute & 0 & 1 & FALSE & 106 & emp: 4660, na: 3669, 45':
1182, 78': 546 \\
home\_bench\_8 & 0 & 1 & FALSE & 3463 & emp: 18228, Giu: 17, Van: 16,
Jos: 15 \\
home\_bench\_8\_minute & 0 & 1 & FALSE & 102 & emp: 18228, na: 2092,
45': 430, 82': 182 \\
away\_bench\_8\_num & 0 & 1 & FALSE & 101 & emp: 18243, 9.0: 338, 11.:
332, 7.0: 310 \\
away\_bench\_8 & 0 & 1 & FALSE & 3462 & emp: 18243, Jos: 17, Fed: 16,
Ani: 13 \\
away\_bench\_8\_minute & 0 & 1 & FALSE & 98 & emp: 18243, na: 1959, 45':
482, 78': 175 \\
away\_bench\_9 & 0 & 1 & FALSE & 2976 & emp: 19134, Ada: 14, Ama: 14,
Mar: 13 \\
away\_bench\_9\_minute & 0 & 1 & FALSE & 98 & emp: 19134, na: 1079, 45':
406, 71': 191 \\
away\_starting\_13 & 0 & 1 & FALSE & 194 & emp: 25383, Álv: 9, Ari: 7,
Lui: 7 \\
home\_bench\_9 & 0 & 1 & FALSE & 3007 & emp: 19031, Ama: 18, Fed: 16,
Ale: 13 \\
home\_bench\_9\_minute & 0 & 1 & FALSE & 96 & emp: 19031, na: 1142, 45':
385, 78': 183 \\
home\_starting\_13 & 0 & 1 & FALSE & 175 & emp: 25417, Jos: 9, Pab: 8,
Ped: 7 \\
home\_starting\_14 & 0 & 1 & FALSE & 97 & emp: 25600, Jua: 3, Lui: 3,
Pab: 3 \\
home\_bench\_10 & 0 & 1 & FALSE & 1774 & emp: 21927, Gré: 16, Cri: 12,
Zak: 11 \\
home\_bench\_10\_minute & 0 & 1 & FALSE & 94 & emp: 21927, 45': 272, na:
135, 74': 130 \\
home\_bench\_11 & 0 & 1 & FALSE & 1373 & emp: 22708, Gor: 15, Cri: 14,
Pat: 14 \\
home\_bench\_11\_minute & 0 & 1 & FALSE & 89 & emp: 22708, 45': 191,
74': 98, 84': 98 \\
away\_bench\_10 & 0 & 1 & FALSE & 1752 & emp: 21950, Gor: 16, Pio: 14,
And: 11 \\
away\_bench\_10\_minute & 0 & 1 & FALSE & 94 & emp: 21950, 45': 299, na:
146, 72': 114 \\
away\_starting\_14 & 0 & 1 & FALSE & 114 & emp: 25569, Jes: 4, Die: 3,
Jos: 3 \\
League & 0 & 1 & FALSE & 6 & Eng: 7979, Spa: 6817, Ger: 6124, Ita:
2270 \\
home\_starting\_15 & 0 & 1 & FALSE & 43 & emp: 25674, Ped: 4, Edu: 2,
Fre: 2 \\
away\_starting\_15 & 0 & 1 & FALSE & 63 & emp: 25654, Álv: 3, Lui: 3,
Alb: 2 \\
away\_starting\_16 & 0 & 1 & FALSE & 31 & emp: 25691, Jos: 2, Jua: 2,
Val: 2 \\
away\_starting\_17 & 0 & 1 & FALSE & 15 & emp: 25710, Alb: 1, Ber: 1,
Giu: 1 \\
away\_bench\_11 & 0 & 1 & FALSE & 1319 & emp: 22851, Pat: 20, Kho: 15,
Ark: 13 \\
away\_bench\_11\_minute & 0 & 1 & FALSE & 84 & emp: 22851, 45': 170,
78': 94, 80': 94 \\
away\_bench\_12 & 0 & 1 & FALSE & 917 & emp: 23771, Gor: 16, Joa: 14,
Sam: 14 \\
away\_bench\_12\_minute & 0 & 1 & FALSE & 80 & emp: 23771, 45': 135,
77': 65, 78': 62 \\
away\_bench\_13 & 0 & 1 & FALSE & 48 & emp: 25675, Jua: 2, Mat: 2, Adr:
1 \\
away\_bench\_13\_minute & 0 & 1 & FALSE & 34 & emp: 25675, 69': 5, 45':
4, 64': 4 \\
home\_starting\_16 & 0 & 1 & FALSE & 18 & emp: 25706, Die: 2, Adr: 1,
Asi: 1 \\
home\_bench\_12 & 0 & 1 & FALSE & 974 & emp: 23628, Joa: 16, Fed: 14,
Ric: 14 \\
home\_bench\_12\_minute & 0 & 1 & FALSE & 87 & emp: 23628, 45': 132,
68': 73, 73': 70 \\
home\_starting\_17 & 0 & 1 & FALSE & 8 & emp: 25717, Fab: 1, Fra: 1,
Jua: 1 \\
home\_bench\_13 & 0 & 1 & FALSE & 42 & emp: 25683, Alb: 1, Ale: 1, Ant:
1 \\
home\_bench\_13\_minute & 0 & 1 & FALSE & 28 & emp: 25683, 45': 3, 64':
3, 73': 3 \\
away\_starting\_18 & 0 & 1 & FALSE & 8 & emp: 25717, Die: 1, Die: 1,
Jan: 1 \\
away\_starting\_19 & 0 & 1 & FALSE & 8 & emp: 25717, Ebi: 1, Iva: 1,
Lau: 1 \\
away\_bench\_14 & 0 & 1 & FALSE & 6 & emp: 25719, Ale: 1, Dav: 1, Del:
1 \\
away\_bench\_14\_minute & 0 & 1 & FALSE & 6 & emp: 25719, 55': 1, 64':
1, 65': 1 \\
home\_starting\_18 & 0 & 1 & FALSE & 5 & emp: 25720, Dav: 1, Hal: 1,
Lui: 1 \\
home\_starting\_19 & 0 & 1 & FALSE & 4 & emp: 25721, Hal: 1, Lui: 1,
Mar: 1 \\
home\_bench\_14 & 0 & 1 & FALSE & 5 & emp: 25720, Cri: 1, Iñi: 1, Jua:
1 \\
home\_bench\_14\_minute & 0 & 1 & FALSE & 5 & emp: 25720, 63': 1, 68':
1, 82': 1 \\
away\_starting\_20 & 0 & 1 & FALSE & 6 & emp: 25719, Cac: 1, Dav: 1,
Mar: 1 \\
away\_starting\_21 & 0 & 1 & FALSE & 5 & emp: 25720, Dan: 1, Ebi: 1,
Luk: 1 \\
home\_starting\_20 & 0 & 1 & FALSE & 3 & emp: 25722, Bou: 1, Mar: 1 \\
home\_starting\_21 & 0 & 1 & FALSE & 3 & emp: 25722, Bou: 1, Mar: 1 \\
away\_starting\_22 & 0 & 1 & FALSE & 3 & emp: 25722, Luk: 1, Rad: 1 \\
home\_bench\_15 & 0 & 1 & FALSE & 2 & emp: 25723, Ian: 1 \\
home\_bench\_15\_minute & 0 & 1 & FALSE & 2 & emp: 25723, 56': 1 \\
\bottomrule()
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1963}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0935}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1308}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0935}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0935}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0561}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0935}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0841}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0935}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0654}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} \\
\midrule()
\endhead
id & 0 & 1.00 & 383131.25 & 161629.48 & 18123 & 252476.75 & 396775.5 &
522549.25 & 614925 \\
year & 0 & 1.00 & 2013.01 & 5.95 & 2001 & 2008.00 & 2014.0 & 2018.00 &
2021 \\
home\_score & 0 & 1.00 & 1.57 & 1.32 & 0 & 1.00 & 1.0 & 2.00 & 10 \\
away\_score & 0 & 1.00 & 1.20 & 1.17 & 0 & 0.00 & 1.0 & 2.00 & 13 \\
home\_foulsCommitted & 2031 & 0.92 & 12.97 & 5.11 & 0 & 10.00 & 13.0 &
16.00 & 37 \\
away\_foulsCommitted & 2031 & 0.92 & 13.31 & 5.23 & 0 & 10.00 & 13.0 &
17.00 & 36 \\
home\_yellowCards & 2031 & 0.92 & 1.81 & 1.34 & 0 & 1.00 & 2.0 & 3.00 &
8 \\
away\_yellowCards & 2031 & 0.92 & 2.09 & 1.39 & 0 & 1.00 & 2.0 & 3.00 &
9 \\
home\_redCards & 2031 & 0.92 & 0.09 & 0.31 & 0 & 0.00 & 0.0 & 0.00 &
3 \\
away\_redCards & 2031 & 0.92 & 0.12 & 0.35 & 0 & 0.00 & 0.0 & 0.00 &
4 \\
home\_offsides & 2031 & 0.92 & 2.34 & 1.95 & 0 & 1.00 & 2.0 & 3.00 &
14 \\
away\_offsides & 2031 & 0.92 & 2.16 & 1.87 & 0 & 1.00 & 2.0 & 3.00 &
17 \\
home\_wonCorners & 2031 & 0.92 & 5.54 & 3.13 & 0 & 3.00 & 5.0 & 7.00 &
20 \\
away\_wonCorners & 2031 & 0.92 & 4.40 & 2.73 & 0 & 2.00 & 4.0 & 6.00 &
20 \\
home\_saves & 2031 & 0.92 & 2.83 & 2.05 & 0 & 1.00 & 3.0 & 4.00 & 18 \\
away\_saves & 2031 & 0.92 & 3.48 & 2.37 & 0 & 2.00 & 3.0 & 5.00 & 18 \\
away\_starting\_12\_num & 24797 & 0.04 & 15.12 & 7.96 & 2 & 9.00 & 14.0
& 19.00 & 91 \\
home\_starting\_12\_num & 24857 & 0.03 & 14.97 & 7.02 & 2 & 10.00 & 14.0
& 19.00 & 69 \\
home\_bench\_8\_num & 18228 & 0.29 & 22.82 & 18.81 & 1 & 11.00 & 19.0 &
28.00 & 99 \\
away\_bench\_9\_num & 19134 & 0.26 & 22.43 & 18.79 & 1 & 10.00 & 19.0 &
27.00 & 99 \\
away\_starting\_13\_num & 25383 & 0.01 & 14.32 & 6.47 & 2 & 9.00 & 12.0
& 19.00 & 43 \\
home\_bench\_9\_num & 19031 & 0.26 & 22.85 & 19.58 & 1 & 10.00 & 19.0 &
27.00 & 99 \\
home\_starting\_13\_num & 25417 & 0.01 & 13.95 & 6.29 & 2 & 9.00 & 12.0
& 18.00 & 40 \\
home\_starting\_14\_num & 25600 & 0.00 & 14.93 & 6.14 & 2 & 10.00 & 14.0
& 19.00 & 33 \\
home\_bench\_10\_num & 21927 & 0.15 & 22.60 & 20.73 & 1 & 10.00 & 18.0 &
26.00 & 99 \\
home\_bench\_11\_num & 22708 & 0.12 & 23.27 & 21.49 & 1 & 10.00 & 17.0 &
27.00 & 99 \\
away\_bench\_10\_num & 21950 & 0.15 & 22.55 & 20.84 & 1 & 9.00 & 17.0 &
26.00 & 99 \\
away\_starting\_14\_num & 25569 & 0.01 & 14.72 & 6.29 & 5 & 9.00 & 14.0
& 19.00 & 33 \\
home\_starting\_15\_num & 25674 & 0.00 & 14.74 & 6.75 & 5 & 9.25 & 13.0
& 21.00 & 33 \\
away\_starting\_15\_num & 25654 & 0.00 & 14.74 & 6.89 & 2 & 9.00 & 14.5
& 20.00 & 35 \\
away\_starting\_16\_num & 25691 & 0.00 & 16.97 & 8.48 & 7 & 10.00 & 16.0
& 22.00 & 38 \\
away\_starting\_17\_num & 25710 & 0.00 & 17.14 & 6.01 & 7 & 12.00 & 18.5
& 21.75 & 27 \\
away\_bench\_11\_num & 22851 & 0.11 & 23.28 & 21.49 & 1 & 10.00 & 17.0 &
27.00 & 99 \\
away\_bench\_12\_num & 23771 & 0.08 & 22.75 & 21.47 & 1 & 10.00 & 17.0 &
25.00 & 99 \\
away\_bench\_13\_num & 25675 & 0.00 & 20.33 & 21.03 & 5 & 9.00 & 14.0 &
22.00 & 99 \\
home\_starting\_16\_num & 25706 & 0.00 & 14.61 & 6.28 & 6 & 9.25 & 12.0
& 18.75 & 27 \\
home\_bench\_12\_num & 23628 & 0.08 & 23.27 & 21.79 & 1 & 10.00 & 17.0 &
27.00 & 99 \\
home\_starting\_17\_num & 25717 & 0.00 & 20.00 & 9.20 & 7 & 14.50 & 18.0
& 26.00 & 34 \\
home\_bench\_13\_num & 25683 & 0.00 & 22.22 & 19.88 & 2 & 9.00 & 20.0 &
25.00 & 90 \\
away\_starting\_18\_num & 25717 & 0.00 & 16.00 & 8.89 & 7 & 9.00 & 14.0
& 22.00 & 29 \\
away\_starting\_19\_num & 25717 & 0.00 & 15.00 & 6.27 & 8 & 9.50 & 14.0
& 20.50 & 23 \\
away\_bench\_14\_num & 25719 & 0.00 & 13.80 & 6.87 & 7 & 9.00 & 11.0 &
19.00 & 23 \\
home\_starting\_18\_num & 25720 & 0.00 & 16.75 & 6.85 & 7 & 15.25 & 18.5
& 20.00 & 23 \\
home\_starting\_19\_num & 25721 & 0.00 & 15.67 & 4.93 & 10 & 14.00 &
18.0 & 18.50 & 19 \\
home\_bench\_14\_num & 25720 & 0.00 & 11.50 & 3.42 & 8 & 9.50 & 11.0 &
13.00 & 16 \\
away\_starting\_20\_num & 25719 & 0.00 & 16.80 & 9.78 & 8 & 11.00 & 14.0
& 18.00 & 33 \\
away\_starting\_21\_num & 25720 & 0.00 & 21.00 & 12.38 & 10 & 13.00 &
18.0 & 26.00 & 38 \\
home\_starting\_20\_num & 25722 & 0.00 & 13.50 & 6.36 & 9 & 11.25 & 13.5
& 15.75 & 18 \\
home\_starting\_21\_num & 25722 & 0.00 & 13.50 & 6.36 & 9 & 11.25 & 13.5
& 15.75 & 18 \\
away\_starting\_22\_num & 25722 & 0.00 & 15.00 & 7.07 & 10 & 12.50 &
15.0 & 17.50 & 20 \\
home\_bench\_15\_num & 25723 & 0.00 & 24.00 & NA & 24 & 24.00 & 24.0 &
24.00 & 24 \\
\bottomrule()
\end{longtable}

\hypertarget{comparing-match-results-with-time.}{%
\subsection{Comparing match results with
time.}\label{comparing-match-results-with-time.}}

In this section we are going to analyze the relation between number of
goals per match and the time the match was taking place.

\hypertarget{changing-format-of-time.}{%
\subsubsection{Changing format of
time.}\label{changing-format-of-time.}}

The first step is changing the format of the column time because this is
recognized as a string and we need R to recognize it as a time format.

For this, we are going to add a new column to the data frame called
``time\_converted''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(matches, }\AttributeTok{time\_converted=}\FunctionTok{hm}\NormalTok{(time..utc.))}
\end{Highlighting}
\end{Shaded}

\hypertarget{calculating-the-total-of-goals-per-match}{%
\subsubsection{Calculating the total of goals per
match}\label{calculating-the-total-of-goals-per-match}}

This data frame has the information of Local score and Visit score but
it does not have the total amount of goals per match.

For this we add a new column where we calculate the total.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(matches, }\AttributeTok{total\_goals =}\NormalTok{ home\_score }\SpecialCharTok{+}\NormalTok{ away\_score)}
\end{Highlighting}
\end{Shaded}

\hypertarget{removing-matches-with-more-than-10-goals}{%
\subsubsection{Removing matches with more than 10
goals}\label{removing-matches-with-more-than-10-goals}}

Games with more than 10 goals are extremely rare and not representative,
that is why they can cause bias, so it has been decided to remove them.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(matches, total\_goals }\SpecialCharTok{\textless{}=}\DecValTok{10}\NormalTok{)}
\NormalTok{League\_insights }\OtherTok{\textless{}{-}}\FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(matches,League),}\AttributeTok{count=}\FunctionTok{n}\NormalTok{(), }\AttributeTok{total\_goals\_mean=}\FunctionTok{mean}\NormalTok{(total\_goals))}
\FunctionTok{View}\NormalTok{(League\_insights)}
\end{Highlighting}
\end{Shaded}

\hypertarget{sun-time}{%
\subsubsection{Sun time}\label{sun-time}}

Our first analysis it will be how the sun can affect the number of goals
in a match.

\hypertarget{differentiating-beetween-sun-time-and-non-sun-time}{%
\subparagraph{Differentiating beetween sun time and non sun
time}\label{differentiating-beetween-sun-time-and-non-sun-time}}

First we will create a new column called sun time, defining sun time as
before 17:00 hours.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(matches, }\AttributeTok{sun\_time =}\NormalTok{ time\_converted }\SpecialCharTok{\textless{}=} \FunctionTok{hm}\NormalTok{(}\StringTok{\textquotesingle{}17:00\textquotesingle{}}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{creating-a-new-table-with-insights}{%
\subsubsection{Creating a new table with
insights}\label{creating-a-new-table-with-insights}}

This table will calculate some insights about the total goals in sun
time and not sun time

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sun\_time\_sum }\OtherTok{\textless{}{-}}\FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(matches,sun\_time), }\AttributeTok{goal\_sum =} \FunctionTok{sum}\NormalTok{(total\_goals), }\AttributeTok{count=}\FunctionTok{n}\NormalTok{(),}
                         \AttributeTok{goal\_mean=}\FunctionTok{mean}\NormalTok{(total\_goals))}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(sun\_time\_sum, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\toprule()
sun\_time & goal\_sum & count & goal\_mean \\
\midrule()
\endhead
FALSE & 23578 & 8584 & 2.746738 \\
TRUE & 47535 & 17135 & 2.774147 \\
\bottomrule()
\end{longtable}

We cant see much difference in the average total of goals.

\hypertarget{visualizing-the-distributions-of-goals-in-football.}{%
\subsubsection{Visualizing the distributions of goals in
football.}\label{visualizing-the-distributions-of-goals-in-football.}}

The table did not give us too much information, so we are going the
compare the distribution of total goals depending on the time, but first
let see how total of goals are distributed in general.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{matches)}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{total\_goals))}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-10-1.pdf}

\hypertarget{visualizing-distribution-of-goals-depending-on-wether-or-not-ther-is-sun.}{%
\subsubsection{Visualizing distribution of goals depending on wether or
not ther is
sun.}\label{visualizing-distribution-of-goals-depending-on-wether-or-not-ther-is-sun.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{matches)}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{total\_goals, }\AttributeTok{y=} \FunctionTok{after\_stat}\NormalTok{(density)),}\AttributeTok{binwidth=}\FloatTok{0.509}\NormalTok{, }\AttributeTok{inherit.aes=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{bins=}\DecValTok{10}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{sun\_time)}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-11-1.pdf}

We can see the are very smilar, but slightly different, and that can be
due the different sample sizes.

\hypertarget{local-and-visit-scores}{%
\subsection{Local and Visit Scores}\label{local-and-visit-scores}}

In the summary of the first chart we can see that the average of local
and visit scores were different.

home score mean is 1.57 and visit score mean is 1.20, lets see how goals
are distribuited depending on this factor \#\#\# Visualizing Home score
and Visit Score rate

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(matches}\SpecialCharTok{$}\NormalTok{home\_score)), }\AttributeTok{main=} \StringTok{"Home score rate"}\NormalTok{, }\AttributeTok{ylab=} \StringTok{"\% of  matches"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"goals"}\NormalTok{)}
\FunctionTok{barplot}\NormalTok{(}\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{table}\NormalTok{(matches}\SpecialCharTok{$}\NormalTok{away\_score)), }\AttributeTok{main=} \StringTok{"Visit score rate"}\NormalTok{, }\AttributeTok{ylab=} \StringTok{"\% of matches"}\NormalTok{, }\AttributeTok{xlab=} \StringTok{"goals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

We can appreciate a clear difference, being way more common a 0 score
for visit in general.

\hypertarget{league-comparation-total-goals}{%
\subsection{League comparation total
goals}\label{league-comparation-total-goals}}

Lets make a visual that shows the total goals distribution for each
League

\hypertarget{total-goals-rate-in-each-european-league-2000-2021}{%
\subsubsection{Total goals rate in each European League
(2000-2021)}\label{total-goals-rate-in-each-european-league-2000-2021}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ matches)}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{mapping =} \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ total\_goals, }\AttributeTok{y=} \FunctionTok{after\_stat}\NormalTok{(density)))}\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{League)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-13-1.pdf}

We can see some differences between them.

\hypertarget{sample-sizes-and-the-average-for-each-league}{%
\subsubsection{Sample sizes and the average for each
League}\label{sample-sizes-and-the-average-for-each-league}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{League }\OtherTok{\textless{}{-}} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(matches,League), }\AttributeTok{count =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{total\_goal\_mean =} \FunctionTok{mean}\NormalTok{(total\_goals)), total\_goal\_mean)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(League, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\toprule()
League & count & total\_goal\_mean \\
\midrule()
\endhead
French Ligue 1 & 1400 & 2.657143 \\
Spanish La Liga & 6816 & 2.666227 \\
English Premier League & 7978 & 2.677864 \\
Italian Serie A & 2270 & 2.872247 \\
German Bundesliga & 6122 & 2.913100 \\
Dutch Eredivisie & 1133 & 3.090909 \\
\bottomrule()
\end{longtable}

In both visual and table we can apreciate that dutch eredivise has less
matches with 0 or 1 goal than the other Leagues, plus the average of
total goals is higher, but the sample size is considerable lower so we
can not take this results as conclusive, but it may be a good start to
further investigations.

\hypertarget{analizing-the-second-table.}{%
\section{Analizing the second
table.}\label{analizing-the-second-table.}}

Now we are going to use the table ``summary'' to get insights. First
lets analyze its distribution.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skim\_without\_charts}\NormalTok{(summary)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule()
\endhead
Name & summary \\
Number of rows & 2484 \\
Number of columns & 12 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
factor & 2 \\
numeric & 10 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule()
\end{longtable}

\textbf{Variable type: factor}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1489}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1064}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1489}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0851}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.0957}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.4149}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ordered
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
top\_counts
\end{minipage} \\
\midrule()
\endhead
Team & 0 & 1 & FALSE & 227 & MON: 38, LEV: 36, BOL: 29, BAR: 25 \\
League & 0 & 1 & FALSE & 6 & Spa: 440, Ita: 432, Eng: 420, Fre: 400 \\
\bottomrule()
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1818}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1299}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1818}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1039}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0779}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0649}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0649}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0649}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0649}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0649}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} \\
\midrule()
\endhead
Place & 0 & 1 & 10.15 & 5.59 & 1 & 5 & 10 & 15 & 20 \\
GP & 0 & 1 & 36.17 & 2.81 & 24 & 34 & 38 & 38 & 38 \\
W & 0 & 1 & 13.47 & 5.58 & 1 & 10 & 12 & 17 & 33 \\
D & 0 & 1 & 9.23 & 3.00 & 0 & 7 & 9 & 11 & 20 \\
L & 0 & 1 & 13.47 & 5.20 & 0 & 10 & 14 & 17 & 29 \\
GF & 0 & 1 & 48.22 & 17.59 & 0 & 38 & 46 & 57 & 121 \\
GA & 0 & 1 & 48.22 & 14.99 & 0 & 40 & 49 & 57 & 98 \\
GD & 0 & 1 & 0.00 & 24.07 & -69 & -16 & -3 & 12 & 89 \\
P & 0 & 1 & 49.57 & 16.05 & 9 & 39 & 46 & 59 & 102 \\
Year & 0 & 1 & 2010.77 & 6.21 & 2000 & 2005 & 2011 & 2016 & 2021 \\
\bottomrule()
\end{longtable}

\hypertarget{champions-insights}{%
\subsection{Champions insights}\label{champions-insights}}

Lets create a new chart that give us insights about the champions of all
the Leagues.

First We have to filter the table to only give us information about
teams in the 1st position, lets remove the year 2000 because it has
incomplete info, also year 2019 because it was suspended due covid 19.

\hypertarget{filtering-champions}{%
\subsubsection{Filtering champions}\label{filtering-champions}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{champions }\OtherTok{\textless{}{-}} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{filter}\NormalTok{(summary, Place}\SpecialCharTok{==}\DecValTok{1}\NormalTok{, Year}\SpecialCharTok{\textgreater{}}\DecValTok{2000}\NormalTok{, Year }\SpecialCharTok{!=} \DecValTok{2019}\NormalTok{), P, GP)}
\end{Highlighting}
\end{Shaded}

Giving that we can create another table with the most important insights

\hypertarget{summary-stats-of-eache-league}{%
\subsubsection{Summary stats of eache
league}\label{summary-stats-of-eache-league}}

This table is going to show how different are the stats of the champions
of each League in the period of time from 2000 to 2021.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insights\_champions }\OtherTok{\textless{}{-}} \FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(champions,League),}\AttributeTok{count=}\FunctionTok{n}\NormalTok{(), }\AttributeTok{total\_points\_mean=}\FunctionTok{mean}\NormalTok{(P), }\AttributeTok{game\_played\_mean=}\FunctionTok{mean}\NormalTok{(GP), }
                                \AttributeTok{Win\_mean=}\FunctionTok{mean}\NormalTok{(W), }\AttributeTok{Lost\_mean=}\FunctionTok{mean}\NormalTok{(L), }\AttributeTok{Draw\_mean=}\FunctionTok{mean}\NormalTok{(D), }\FunctionTok{max}\NormalTok{(P), }\FunctionTok{min}\NormalTok{(P), }\AttributeTok{number\_champions=}\FunctionTok{n\_distinct}\NormalTok{(Team))}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(insights\_champions, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1855}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0484}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1452}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1371}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0726}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0806}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0806}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0565}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.0565}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 18\tabcolsep) * \real{0.1371}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
League
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
count
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
total\_points\_mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
game\_played\_mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Win\_mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Lost\_mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Draw\_mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max(P)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min(P)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
number\_champions
\end{minipage} \\
\midrule()
\endhead
Dutch Eredivisie & 20 & 80.55000 & 34.00000 & 24.90000 & 3.250000 &
5.850000 & 88 & 71 & 5 \\
English Premier League & 20 & 88.85000 & 37.95000 & 27.45000 & 4.000000
& 6.500000 & 100 & 80 & 5 \\
French Ligue 1 & 19 & 83.26316 & 37.94737 & 24.94737 & 4.578947 &
8.421053 & 96 & 68 & 7 \\
German Bundesliga & 20 & 77.95000 & 34.00000 & 23.95000 & 3.950000 &
6.100000 & 91 & 69 & 5 \\
Italian Serie A & 20 & 85.90000 & 37.35000 & 26.05000 & 3.550000 &
7.750000 & 102 & 71 & 3 \\
Spanish La Liga & 20 & 87.90000 & 37.95000 & 27.00000 & 4.050000 &
6.900000 & 100 & 75 & 4 \\
\bottomrule()
\end{longtable}

\hypertarget{most-wining-teams-in-europe}{%
\subsection{Most wining teams in
Europe}\label{most-wining-teams-in-europe}}

In order to see which teams have more titles, we can create a
visualization. But first lets filter our table ``champions'' ton only
contain info about teams with 3 or more titles.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insights\_champions\_team }\OtherTok{\textless{}{-}} \FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(champions, Team, League),}\AttributeTok{count=}\FunctionTok{n}\NormalTok{(), }\AttributeTok{total\_points\_mean=}\FunctionTok{mean}\NormalTok{(P), }\AttributeTok{game\_played\_mean=}\FunctionTok{mean}\NormalTok{(GP), }
                                \AttributeTok{Win\_mean=}\FunctionTok{mean}\NormalTok{(W), }\AttributeTok{Lost\_mean=}\FunctionTok{mean}\NormalTok{(L), }\AttributeTok{Draw\_mean=}\FunctionTok{mean}\NormalTok{(D), }\FunctionTok{max}\NormalTok{(P), }\FunctionTok{min}\NormalTok{(P))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Team'. You can override using the
## `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insights\_champions\_winners }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(insights\_champions\_team, count }\SpecialCharTok{\textgreater{}=} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now lets create a Viz showing this.

\hypertarget{showing-the-most-winning-teams.}{%
\subsubsection{Showing the most winning
teams.}\label{showing-the-most-winning-teams.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{insights\_champions\_winners)}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(Team, }\SpecialCharTok{{-}}\NormalTok{count), }\AttributeTok{y =}\NormalTok{ count, }\AttributeTok{fill =}\NormalTok{ League), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position=}\StringTok{"dodge"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"Teams"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Championships"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Most winning teams in Europe (2001{-}2021)"}
\NormalTok{    )}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-19-1.pdf}

We can apreciate that Bayern Munich its the most winning team in Europe
from 2000 to 2021.

\hypertarget{most-dominated-leagues}{%
\subsection{Most dominated Leagues}\label{most-dominated-leagues}}

Lets create a Viz which tell us how many different teams have won their
League in the period (2000-2021)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{insights\_champions)}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(League, }\SpecialCharTok{{-}}\NormalTok{number\_champions), }\AttributeTok{y =}\NormalTok{ number\_champions, }\AttributeTok{fill =}\NormalTok{ League), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position=}\StringTok{"dodge"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"League"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"different champions"}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Number of different champions in each League (2001{-}2021)"}
\NormalTok{  )}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-20-1.pdf}

We can see that Italian Serie A is the most dominated League with only 3
different champions in more than 20 years.

\hypertarget{rate-of-championships}{%
\subsection{Rate of championships}\label{rate-of-championships}}

Lets see the rate of champions of each League.

First lets create a single table for each League containing all the
champions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Dutch }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"Dutch Eredivisie"}\NormalTok{))}
\NormalTok{Spanish }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"Spanish La Liga"}\NormalTok{))}
\NormalTok{English }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"English Premier League"}\NormalTok{))}
\NormalTok{German }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"German Bundesliga"}\NormalTok{))}
\NormalTok{Italian }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"Italian Serie A"}\NormalTok{))}
\NormalTok{French }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{filter}\NormalTok{(insights\_champions\_team, League }\SpecialCharTok{==} \StringTok{"French Ligue 1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Creating the pie charts to see the rates.

\hypertarget{showing-the-rate-of-all-the-championships-in-each-league-2000-2021}{%
\subsubsection{Showing the rate of all the championships in each League
(2000-2021)}\label{showing-the-rate-of-all-the-championships-in-each-league-2000-2021}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{))}
\FunctionTok{pie}\NormalTok{(Dutch}\SpecialCharTok{$}\NormalTok{count,Dutch}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate Dutch Eredivise"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(Dutch}\SpecialCharTok{$}\NormalTok{Team)))}
\FunctionTok{pie}\NormalTok{(Spanish}\SpecialCharTok{$}\NormalTok{count,Spanish}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate Spain"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(Spanish}\SpecialCharTok{$}\NormalTok{Team)))}
\FunctionTok{pie}\NormalTok{(English}\SpecialCharTok{$}\NormalTok{count,English}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate English"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(English}\SpecialCharTok{$}\NormalTok{Team)))}
\FunctionTok{pie}\NormalTok{(German}\SpecialCharTok{$}\NormalTok{count,German}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate German"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(Italian}\SpecialCharTok{$}\NormalTok{Team)))}
\FunctionTok{pie}\NormalTok{(Italian}\SpecialCharTok{$}\NormalTok{count,Italian}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate Italian"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(French}\SpecialCharTok{$}\NormalTok{Team)))}
\FunctionTok{pie}\NormalTok{(French}\SpecialCharTok{$}\NormalTok{count,French}\SpecialCharTok{$}\NormalTok{Team, }\AttributeTok{main=} \StringTok{"Championship rate French"}\NormalTok{, }\AttributeTok{col =} \FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(French}\SpecialCharTok{$}\NormalTok{Team)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{difficulty}{%
\subsection{Difficulty}\label{difficulty}}

Lets see how difficult is to become a champion in each League, for this
we are gonna measure it with the win rate (win games/ total games) the
higher win rate is in general, the harder to become a champion.

For that we have to create a new column in the table ``champions''
calculating the ``win\_rate''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{champions }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(champions, }\AttributeTok{win\_rate=}\NormalTok{ W}\SpecialCharTok{/}\NormalTok{GP) }
\end{Highlighting}
\end{Shaded}

Taking the data of the previous table lets create a new one with the
main insights about win rate for each League.

\hypertarget{win-rate}{%
\subsubsection{Win Rate}\label{win-rate}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{insights\_wr }\OtherTok{\textless{}{-}} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{summarize}\NormalTok{(}\FunctionTok{group\_by}\NormalTok{(champions, League), }\AttributeTok{WR\_mean=}\FunctionTok{mean}\NormalTok{(win\_rate), }\AttributeTok{WR\_max=}\FunctionTok{max}\NormalTok{(win\_rate), }\AttributeTok{WR\_min=}\FunctionTok{min}\NormalTok{(win\_rate)), WR\_mean)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(insights\_wr, }\AttributeTok{format =} \StringTok{"markdown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\toprule()
League & WR\_mean & WR\_max & WR\_min \\
\midrule()
\endhead
French Ligue 1 & 0.6574455 & 0.7894737 & 0.5000000 \\
Italian Serie A & 0.6966321 & 0.8684211 & 0.5882353 \\
German Bundesliga & 0.7044118 & 0.8529412 & 0.5882353 \\
Spanish La Liga & 0.7114509 & 0.8421053 & 0.5526316 \\
English Premier League & 0.7233642 & 0.8421053 & 0.6052632 \\
Dutch Eredivisie & 0.7323529 & 0.8529412 & 0.5882353 \\
\bottomrule()
\end{longtable}

Lets see the difference in average of champion's win rate

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{insights\_wr)}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(League, }\SpecialCharTok{{-}}\NormalTok{WR\_mean), }\AttributeTok{y =}\NormalTok{ WR\_mean, }\AttributeTok{fill =}\NormalTok{ League), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position=}\StringTok{"dodge"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"League"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Average of champion\textquotesingle{}s Win rate "}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Average Win rate to be champion"}
\NormalTok{  )}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{))  }
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-25-1.pdf}

Lets see the historical minimun Win Rate to become a champion in each
League.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{insights\_wr)}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{mapping=}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(League, }\SpecialCharTok{{-}}\NormalTok{WR\_min), }\AttributeTok{y =}\NormalTok{ WR\_min, }\AttributeTok{fill =}\NormalTok{ League), }\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{position=}\StringTok{"dodge"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{x =} \StringTok{"League"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"min champion\textquotesingle{}s Win rate "}\NormalTok{,}
    \AttributeTok{title =} \StringTok{"Historical min Win rate to be champion (2000{-}2021)"}
\NormalTok{  )}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{trabajo_notebook_files/figure-latex/unnamed-chunk-26-1.pdf}

\end{document}
